### ISSUE TITLE
Files for field RELEASES are missing

### ISSUE THREAD

**Issue by Ludee** [rl-institut/super-repo#11]
**RELEASES**
- [x] RELEASE_PROCEDURE.md
- [x] MANIFEST.in
- [x] .bumpversion.cfg
- [x] GitHub Action for PyPI

Releases are following the [Semantic Versioning (SemVer)](https://semver.org/).
To follow the standard, this part should be considered:

> Is “v1.2.3” a semantic version?
No, “v1.2.3” is not a semantic version. However, prefixing a semantic version with a “v” is a common way (in English) to indicate it is a version number. Abbreviating “version” as “v” is often seen with version control. Example: git tag v1.2.3 -m "Release version 1.2.3", in which case “v1.2.3” is a tag name and the semantic version is “1.2.3”.

**Comment by jh-RLI** [comment]
The VERSION file is not required for code repositories that are created as a so-called package (in Python). In this case, the version is managed in setup.py. A repository like eoeplatform needs an additional source to store the version. 

If the project uses bump2version the version in maintained in the `.bumpversion.cfg` file. This files also specifyies all sources that must be updated by each release (like the `VERSION` or the `setup.py` files).
