### ISSUE TITLE
Include usefull info and setups from rli_template

### ISSUE THREAD

**Issue by jh-RLI** [rl-institut/super-repo#12]
Should this repo also be a github template repo? It would be nice to make it easy to create a new repo based on this one.
How this repo will be different from the other template repos? Should we focus here on setting up tests and code CI as well
as code continuous delivery methods?

**Comment by jh-RLI** [comment]
@Ludee  I can't assign anyone to this issue

**Comment by Ludee** [comment]
While the [rli_template](https://github.com/rl-institut/rli_template) is focusing on technical stuff, this repo starts with the collaborative and community features. I would rather go step by step and first setup a proper scientific documentation before adding technical features.
Your help on #4 is welcome!

**Comment by Ludee** [comment]
> @Ludee I can't assign anyone to this issue

I updated the user rights, please check again.

**Comment by jh-RLI** [comment]
Works now :)

**Comment by jh-RLI** [comment]
That sounds great, I just wanted to make sure we don't overlook the work that has already been done in the other repos. As I work on my master's thesis, I'm adding my research on these topics  (we discussed this already).
