### ISSUE TITLE
Include CI from Python Package Skeleton Template

### ISSUE THREAD

**Issue by Ludee** [rl-institut/super-repo#21]
## Description of the issue
I just found an existing repo template that has well documented CI structures.
https://github.com/joaomcteixeira/python-project-skeleton

## Ideas of solution
Merge or import the features.
Give proper attribution.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
The CI structure documented in the repo is good, but it uses `tox`, which might be overkill for many smaller projects. In this case, I suggest to just use pytest. Tox is good for running tests in multiple environments (for multiple Python versions) and also for setting up the infrastructure first to run integration tests (tests that check functions that depend on other functions/services). 

In any case, to demonstrate the basic TDD workflow to beginners, it is better to start without Tox. With pytest you can implement tests that fail without any overhead. Then the functionality is implemented and the test is executed again until all tests pass successfully.

[Edit]
I will just implement it using tox ... we can still create a guide that uses pytest.

**Comment by jh-RLI** [comment]
For some reason this was not closed after the merge. Do you want to keep this issue open? @Ludee

**Comment by Ludee** [comment]
The repo is missing the **bumpversion** function. Do we want to include this?

**Comment by jh-RLI** [comment]
Yes, it is very helpful to remember to update the versions of files & minimized manual effort. Its setup quite  is also simple.

**Comment by Ludee** [comment]
I updated isort and flake8 with ruff. Works great.
