### ISSUE TITLE
CODE STYLE is missing 

### ISSUE THREAD

**Issue by Ludee** [rl-institut/super-repo#22]
## Description of the issue

Add guidelines for code styles.

## Ideas of solution

- https://github.com/psf/black
- https://google.github.io/styleguide/pyguide.html
- #30

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md)

**Comment by jh-RLI** [comment]
I will add some initial content i created.
