### ISSUE TITLE
Source code directory name `src`

### ISSUE THREAD

**Issue by jh-RLI** [rl-institut/super-repo#23]
## Description of the issue

As it we discussed about the name of the source dir... 
the `src` is meant as placeholder for the actual module. It can include sub modules of course. But for some use cases its more clean to  have a structure like `module-name/`... rather then `src/module-name folder/`... .

## Ideas of solution

Rename folder

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md)

**Comment by Ludee** [comment]
As discussed today we follow the **Hitchhiker’s Guide to Python** and remove the `src` folder.

> Your library does not belong in an ambiguous src or python subdirectory.

source: https://docs.python-guide.org/writing/structure/#the-actual-module
