### ISSUE TITLE
Files for INSTALL and dependency management are missing

### ISSUE THREAD

**Issue by jh-RLI** [rl-institut/super-repo#24]
## Description of the issue

Since I introduced a requiements.txt file, it was discussed if there was a better solution. In modern Python repos. poetry or a similar package dependency manager is installed, which automatically tracks versions and other metadata about the package installation. An environment.yml file could also be useful (e.g. for conda), but is not necessary as far as I know.

## Ideas of solution

Describe possible ideas for solution and evaluate advantages and disadvantages.

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md)

**Comment by Ludee** [comment]
This should be done with [uv](https://github.com/astral-sh/uv)
