### ISSUE TITLE
Pre-commit and Pre-commit hooks are missing

### ISSUE THREAD

**Issue by henhuy** [rl-institut/super-repo#30]
## Pre-commit

Pre-commit comes in very handy for detecting format/linter/etc. errors before committing them to the repo.
I would at least add flake8 and black as pre-commit hooks.

## Ideas of solution

- add `.pre-commit-config.yaml` to repo
- add hooks to pre-commit file (recommended: flake8, black, ruff and stuff from https://github.com/pre-commit/pre-commit-hooks)
- include pre-commit advice in `CONTRIBUTING.md`

**Comment by nesnoj** [comment]
Yes, that'd be great. You may wanna have a look on some working implementations in
- https://github.com/rl-institut-private/digipipe
- https://github.com/rl-institut-private/digiplan
- https://github.com/openego/eDisGo
- https://github.com/openego/eGon-data

**Comment by jh-RLI** [comment]
I will add the hook now :)

Note:
Flake8 & isort are now also part of the example CI setup. Since we are using Tox, it is easy to run the test suite locally along with linting.

**Comment by Ludee** [comment]
Also have a look at: 
- https://github.com/sedos-project/pipeline (black)
- https://github.com/sedos-project/data_adapter (ruff)

**Comment by jh-RLI** [comment]
> Also have a look at:
> 
> * https://github.com/sedos-project/pipeline (black)
> * https://github.com/sedos-project/data_adapter (ruff)

i added both 👍

**Comment by Ludee** [comment]
I will test and reproduce now. Thanks a lot!

**Comment by jh-RLI** [comment]
There is also a mkdocs page at `development/git/pre-commit/` not sure if this will be the final place.
