### ISSUE TITLE
Files for field DOCUMENTATION are missing

### ISSUE THREAD

**Issue by Ludee** [rl-institut/super-repo#4]
**DOCUMENTATION**
- [x] CHANGELOG.md #6
- [x] README.rst #8 #10
- [x] Evaluate and decide documentation tool (Read the docs, mkdocs, docsaurus...)
- [x] MkDocs #14
- [x] mkdocstrings #20
- [x] Publish documentation #25
- [x] Enable versioning 

**Additional**
- [x] requirements.txt to ease environment installation

**Comment by jh-RLI** [comment]
Within the next weeks (probably next week) I will be able to provide detailed information on what documentation tool we should use here. Still in favor of: 
1. mkdocs for basic "not so shiny" technical documentation (based on python - best option for pure python software)
2. docsaurus for a shiny look and more interactive UI for technical + general documentation (based on node.js - very common in many projects globally - not that common in rli projects - still easy to install and manage)

**Comment by Ludee** [comment]
We decided for **mkdocs** as default documentation package and _material_ as default style.
https://pypi.org/project/mkdocs/
https://pypi.org/project/mkdocs-material/
https://squidfunk.github.io/mkdocs-material/

**Comment by Ludee** [comment]
In general, the documentation should be in a folder called **doc** or **documentation**.
Looking at (all) other repositories and tools it is common practice to call it **docs**.
It is neither a proper English word nor does it follow the principle of not using plural for names and folders, but ...

**Comment by Ludee** [comment]
For publishing and deploying the documentation on a **GitHub Page** with an **GitHub Action** this file is necessary:

- `.github\workflows\gh-pages.yml`

**Comment by Ludee** [comment]
Versions in MkDocs are done with **mike**. They need to be set manually after the release. 
The develop branch is build using the workflow `gh-pages.yml`
