### ISSUE TITLE
Good GitHub Labels are missing

### ISSUE THREAD

**Issue by Ludee** [rl-institut/super-repo#46]
## Description of the issue

There are only standard GitHub Labels.

## Ideas of solution

Search for a nice set of suitable and useful labels to structure issues and PR.
Discuss to also include emoticons. 

Sources:
- https://docs.github.com/en/issues/using-labels-and-milestones-to-track-work/managing-labels
- https://seantrane.com/posts/logical-colorful-github-labels-18230/
- https://medium.com/@dave_lunny/sane-github-labels-c5d2e6004b63
- https://unremarkabletester.com/2021/07/05/small-tips-for-organising-github-labels/

Examples:
- https://github.com/OpenEnergyPlatform/open-MaStR/labels
- https://github.com/freeCodeCamp/freeCodeCamp/labels?page=2&sort=name-asc
- https://github.com/hashicorp/nomad/labels

Best-Practice:
- Create useful labels, but not too many (1 Page!)
- Group by category for better sorting (e.g. type:bug)
- Use nice colours
- Add an emoticon in the end

## Workflow checklist
- [x] I am aware of the workflow in [CONTRIBUTING.md](https://github.com/rl-institut/super-repo/blob/develop/CONTRIBUTING.md)

**Comment by Ludee** [comment]
Categories:
- **type**:
    - bug :bug: "Something isn't working" [default] #E74C3C
    - feature :hammer_and_wrench: "New feature or request" #3498DB
    - enhancement :gear: "Improvement of an existing feature" [default] #27AE60
    - question :question: "Further information is requested" [default] #FFD700
    - release :rocket: "Release procedure" #9B59B6
- **part**:
    - backend :bricks: "Backend component" #34495E
    - frontend :desktop_computer: "Improvement of design or content" #1ABC9C
    - docu :book: "Improvements or additions to documentation" [default] #95A5A6
    - github :octocat: "Improvement of the organisation or repo" #7140C9
    - community :earth_africa: "Concerns the community" #9EB7EA
- **status**:
    - active :construction: "Work in progress" #3498DB
    - blocked :stop_sign: "Blocked or impeded progress" #E74C3C
    - discussion :speech_balloon: "Discussion is ongoing" #FFC300
    - decision wanted :ballot_box: "Decision is needed" #FBCA04
    - completed :heavy_check_mark: "Task has been completed" #27AE60
- **priority**:
    - low :sloth: "Low priority" #95A5A6
    - high :zap: "High priority" #E67E22
    - critical :fire: "Critical priority" #D35400
- resolution:
    - released :tada: "Resolved and released" #9B59B6
    - wontfix :no_entry: "This will not be worked on" [default] #4E6664
    - invalid :x: "Issue is invalid" [default] #E74C3C
    - duplicate :feet: "This issue or pull request already exists" [default] #E74C3C
- other:
    - good first issue :seedling: "Good for newcomers" [default] #2ECC71
    - help wanted :raising_hand: "Help or assistance is needed" [default] #3498DB
    - example :triangular_ruler: "Provides an example" #D4C5F9
    
 Created using this prompt:
>Here is a list of "GitHub Labels" and their categories. Find a suitable emoticon for each and add a short and informative description. Find suitable colors (hex code) for each label, consider the categories:

**Comment by Ludee** [comment]
All labels have been created and implemented for open and closed issues and PR.

**Comment by Ludee** [comment]
Issue templates need an update!

**Comment by jh-RLI** [comment]
Import/export lables
https://gist.github.com/MoOx/93c2853fee760f42d97f?permalink_comment_id=4162292#gistcomment-4162292

**Comment by Ludee** [comment]
```JSON
[
    {
        "name": "other: example 📐",
        "description": "Provides an example",
        "color": "EBF0F3"
    },
    {
        "name": "other: good first issue 🌱",
        "description": "Good for newcomers",
        "color": "EBF0F3"
    },
    {
        "name": "other: help wanted 🙋",
        "description": "Help or assistance is needed",
        "color": "EBF0F3"
    },
    {
        "name": "part: backend 🧱",
        "description": "Backend component",
        "color": "A7F3D5"
    },
    {
        "name": "part: community 🌍",
        "description": "Concerns the community",
        "color": "A7F3D5"
    },
    {
        "name": "part: docu 📖",
        "description": "Improvements or additions to documentation",
        "color": "A7F3D5"
    },
    {
        "name": "part: frontend 🖥️",
        "description": "Improvement of design or content",
        "color": "A7F3D5"
    },
    {
        "name": "part: github",
        "description": "Improvement of the organisation or repo",
        "color": "A7F3D5"
    },
    {
        "name": "priority: critical 🔥",
        "description": "Critical priority",
        "color": "FCA5A5"
    },
    {
        "name": "priority: high ⚡",
        "description": "High priority",
        "color": "FDBA74"
    },
    {
        "name": "priority: low 🦥",
        "description": "Low priority",
        "color": "FCD34D"
    },
    {
        "name": "resolution: duplicate 🐾",
        "description": "This issue or pull request already exists",
        "color": "ECDCF8"
    },
    {
        "name": "resolution: invalid ❌",
        "description": "Issue is invalid",
        "color": "ECDCF8"
    },
    {
        "name": "resolution: released 🎉",
        "description": "Resolved and released",
        "color": "ECDCF8"
    },
    {
        "name": "resolution: wontfix ⛔",
        "description": "This will not be worked on",
        "color": "ECDCF8"
    },
    {
        "name": "status: active 🚧",
        "description": "Work in progress",
        "color": "93C5FD"
    },
    {
        "name": "status: blocked 🛑",
        "description": "Blocked or impeded progress",
        "color": "F9A8D4"
    },
    {
        "name": "status: completed ✔️",
        "description": "Task has been completed",
        "color": "6EE7B7"
    },
    {
        "name": "status: decision wanted 🗳️",
        "description": "Decision is needed",
        "color": "F9A8D4"
    },
    {
        "name": "status: discussion 💬",
        "description": "Discussion is ongoing",
        "color": "93C5FD"
    },
    {
        "name": "type: bug 🐛",
        "description": "Something isn't working",
        "color": "FEF1C7"
    },
    {
        "name": "type: enhancement ⚙️",
        "description": "Improvement of an existing feature",
        "color": "FEF1C7"
    },
    {
        "name": "type: feature 🛠️",
        "description": "New feature or request",
        "color": "FEF1C7"
    },
    {
        "name": "type: question ❓",
        "description": "Further information is requested",
        "color": "FEF1C7"
    },
    {
        "name": "type: release 🚀",
        "description": "Release procedure",
        "color": "FEF1C7"
    }
]
```

**Comment by Ludee** [comment]
Implement updated colour palette:
https://github.com/OpenEnergyPlatform/oemetadata/issues/208
