### ISSUE TITLE
Files for field TESTS are missing

### ISSUE THREAD

**Issue by Ludee** [rl-institut/super-repo#61]
**TESTS**

- [x] CI #21
- [x] pytest.ini
- [x] .coveragerc (Code coverage) / codecov
- [x] --.mypy.ini  (type checker)--
- [x] tox

**Comment by jh-RLI** [comment]
I will add tests + documentation this week / early next week.

- A coverage report is already generated. If you install Tox and then run it (type `tox` in the command line). Nowadays, simple coverage reports are rather criticized, as they say nothing about the quality of the tests and can be intentionally faked. Nevertheless, I will add the documentation on how to view the report, I just wanted to provide this background.

**Comment by Ludee** [comment]
Revise: https://enterprisecraftsmanship.com/posts/you-naming-tests-wrong/

`<method>_Should<expected>_When<condition>`

**Comment by Ludee** [comment]
Test: Load file
```python
def test_FILE_should_load():
    try:
        from path.file import FILE
    except Warning:
        print("Cannot open file!")
```

**Comment by Ludee** [comment]
Codecov implemented and badge finally works
