### ISSUE TITLE
Create and compile a perfect README for repos

### ISSUE THREAD

**Issue by Ludee** [rl-institut/super-repo#8]
**Literature review:**

- https://bulldogjob.com/readme/how-to-write-a-good-readme-for-your-github-project
- https://www.readme-templates.com/
- https://thoughtbot.com/blog/how-to-write-a-great-readme
- https://tom.preston-werner.com/2010/08/23/readme-driven-development.html
- https://changelog.com/posts/top-ten-reasons-why-i-wont-use-your-open-source-project
- https://github.com/18F/open-source-guide/blob/18f-pages/pages/making-readmes-readable.md
- https://www.freecodecamp.org/news/how-to-write-a-good-readme-file/
- https://tom.preston-werner.com/2010/08/23/readme-driven-development.html

**Structure:**

- Badges
- Title and logo
- Contents
- About
- Documentation
   - Installation
   - User Documentation
   - Developer Documentation
- Collaboration
- License and citing
- Contact

**File format:**
MD: 
- Easy to use
- Easy syntax for links

RST:
- Automated table of content with links
- Easy structure of tables
- Easy embedding of badges

**Comment by Ludee** [comment]
Example SVG for repo logo:
![OpenEnergyFamily_Logo_Super-Repo](https://user-images.githubusercontent.com/14353512/185414840-9143c813-c65c-4889-b838-e08085a85382.svg)

**Comment by Ludee** [comment]
There are problems with aligning an image to the right in RST
![super-repo_rli_header](https://user-images.githubusercontent.com/14353512/185425447-85dbcde9-f3a2-4f06-a2db-0dee43af2f5f.png)
.

**Comment by Bachibouzouk** [comment]
I found this a nice check-list for writing readme: https://github.com/ddbeck/readme-checklist/blob/main/checklist.md
